FROM docker.io/library/debian:trixie
COPY --chown=ubuntu:ubuntu plexhelp-commander-web/target/plexhelp-commander /home/ubuntu/commander
RUN chmod +x /home/ubuntu/commander
WORKDIR /home/ubuntu
USER ubuntu
ENTRYPOINT ["sh", "-c", "/home/ubuntu/commander"]

