FROM docker.io/library/debian:trixie
RUN mkdir -p /app && chown -R ubuntu:ubuntu /app
COPY --chown=ubuntu:ubuntu plexhelp-commander-web/target/plexhelp-commander /app/commander
RUN chmod +x /app/commander
WORKDIR /app
USER ubuntu
ENTRYPOINT ["sh", "-c", "/app/commander"]

