spring:
  application:
    name: commander
  threads:
    virtual:
      enabled: true
  thymeleaf:
    check-template-location: false

  data:
    mongodb:
      auto-index-creation: true

  mongodb:
    database: videosmover_dev
    uri: mongodb://mongoConnectionString

  jackson:
    use-jackson2-defaults: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  file:
    name: vm-commander_dev.log

togglz:
  cache:
    enabled: true
    time-to-live: 10000

torrent:
  webui:
    baseUrl: <QTorrent Base URL>
    username: <webUI username>
    password: <webUI password>
    read-timeout: 5000

token:
  security:
    type: SECRET
    secret:
      algo: NONE
    issuer: auth-service-dev

tmdb:
  client:
    api-key: myApiKey
    base-url: https://api.themoviedb.org
    read-timeout: 5000

online:
  result-limit: 10
  poster-base: https://image.tmdb.org/t/p/w92

server:
  command:
    name: winprime
    listen-cron: "0/10 0/1 * 1/1 * ? *"
    wsl:
      enabled: false
      system32-path: "/mnt/c/Windows/System32/"
    ssh:
      enabled: false
      port: 22
      host: localhost
      username: changeMe
      password: changeMe
  tomcat:
    threads:
      max: 10
      min-spare: 3

filesystem:
  downloads-path: /Downloads
  movies-path: /Movies
  tv-path: /TV
  cache:
    cron: "0 * * * * *"

search:
  max-depth: 2
  exclude-paths:
    - /a/path/to/exclude/from/media/search
    - /another/path/to/exclude/from/media/search
  video-min-size-bytes: 104857600
  video-mime-types:
    - video/x-matroska
    - video/x-msvideo
    - video/mp4
    - video/x-flv
    - video/quicktime
    - video/x-ms-wmv
    - video/vnd.dlna.mpeg-tts
    - application/x-matroska

rename:
  trim-regex:
    - .[sS](\d{1,2})([-]?[eE](\d{1,2}))?
    - "[\\.\\s][sS][0-9]{1,2}[\\.\\s]?"
    - 1080p
    - 720p
    - 2160p
    - BluRay
    - HDTV
    - x264
    - REPACK
    - WEB-DL
    - BRRip
    - H264
    - AAC
    - XviD
    - AC3
    - HDRip
    - DVDRip
    - WEBRip
    - DVDScr
    - HQ
    - KORSUB
    - BDRip
    - ".?RARBG"
    - "(\\d|\\.){1,5}(GB|MB)"
    - "\\.EXTENDED\\."
    - MP3
    - "(DD)?5\\.1"
    - DTS
    - "Season \\d{1}"
    - DUBBED
  similarity-percent: 80
  max-depth: 3

move:
  restricted-remove-paths:
    - someFolder1
    - some/folder/to/exclude/from/delete/2
  subs-ext:
    - .srt
    - .sub
    - .ssa
    - .ass
    - .usf
    - .idx
    - .ssf
    - .stl
    - .smi
    - .rt
    - .psb
    - .pjs
    - .ttxt
    - .jss
    - .gsub
    - .aqt
    - .nfo
  subs-max-depth: 5

automove:
  cron: "*/10 * * * * *"
  limit: 50
  similarityAccepted: 85
